# Generated by Django 3.2.11 on 2022-06-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('select gender', 'SELECT GENDER'), ('male', 'MALE'), ('female', 'FEMALE'), ('prefer not to say', 'PREFER NOT TO SAY')], default='male', max_length=50),
        ),
    ]
