# Generated by Django 3.2.11 on 2022-06-12 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_registry', '0003_auto_20220610_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
    ]
